const TYPE_STYLE = {
  unused_subscription: { label: 'Cut', className: 'text-leak border-leak/40 bg-leak-soft/40' },
  anomaly: { label: 'Notice', className: 'text-stamp border-stamp/30 bg-stamp/5' },
  trend: { label: 'Trend', className: 'text-ink-soft border-line bg-paper-raised' },
  summary: { label: 'Summary', className: 'text-saved border-saved/40 bg-saved-soft/40' },
}

export default function InsightsFeed({ insights, loading, generating, onGenerate, providerName }) {
  return (
    <div>
      <div className="flex items-center justify-between mb-3">
        <h2 className="font-display text-lg text-ink">Auditor's notes</h2>
        <button
          onClick={onGenerate}
          disabled={generating}
          className="font-mono text-xs uppercase tracking-wide px-3 py-1.5 rounded border border-line text-ink-soft hover:border-stamp hover:text-stamp transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {generating ? 'Reading the ledger…' : 'Regenerate'}
        </button>
      </div>

      {loading ? (
        <div className="space-y-3">
          {[0, 1].map((i) => (
            <div key={i} className="h-16 animate-pulse bg-line/40 rounded" />
          ))}
        </div>
      ) : insights.length === 0 ? (
        <div className="border border-dashed border-line rounded p-6 text-center">
          <p className="font-body text-sm text-ink-soft mb-3">
            No notes yet. Generate a read on your current spending.
          </p>
          <button
            onClick={onGenerate}
            disabled={generating}
            className="font-mono text-xs uppercase tracking-wide px-4 py-2 rounded bg-stamp text-paper hover:opacity-90 transition-opacity disabled:opacity-50"
          >
            {generating ? 'Reading the ledger…' : 'Generate notes'}
          </button>
        </div>
      ) : (
        <ul className="space-y-3">
          {insights.map((insight) => {
            const style = TYPE_STYLE[insight.insight_type] ?? TYPE_STYLE.trend
            return (
              <li key={insight.id} className={`border rounded p-3 ${style.className}`}>
                <div className="flex items-center gap-2 mb-1">
                  <span className="font-mono text-[10px] uppercase tracking-[0.15em] opacity-70">
                    {style.label}
                  </span>
                  {insight.potential_monthly_savings > 0 && (
                    <span className="font-mono text-[10px] uppercase tracking-[0.15em] opacity-70">
                      · ${insight.potential_monthly_savings.toFixed(2)}/mo
                    </span>
                  )}
                </div>
                <p className="font-body font-medium text-ink text-sm">{insight.headline}</p>
                <p className="font-body text-ink-soft text-sm mt-0.5">{insight.body}</p>
              </li>
            )
          })}
        </ul>
      )}

      {!loading && insights.length > 0 && (
        <p className="font-mono text-[10px] text-ink-soft/60 mt-3 uppercase tracking-wide">
          generated by {providerName === 'vertex-ai' ? 'Vertex AI' : 'local rules engine (no API key configured)'}
        </p>
      )}
    </div>
  )
}
